### ISSUE TITLE
Amélioration des seeds images...

### ISSUE THREAD

**Issue by GoharSam** [LisaMarchetti/ROAD_TRIP#16]

**Comment by CaLy974** [comment]
modified:   app/views/layouts/application.html.erb => map-zoom-modified
<img width="790" alt="Screen Shot 2022-12-02 at 2 08 36 PM" src="https://user-images.githubusercontent.com/113687023/205300118-4670c880-e624-483a-8241-a35bd2c4f11f.png">

modified:   app/views/shared/_banner.html.erb => banner-img-modified
modified:   db/seeds.rb => seeds-img-update + add a user0 for toto.

**Comment by CaLy974** [comment]
J'ai fais un push de ma branche. Elle est en attente sur github du coup.
